name: Daily Python API Call

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 06:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render API
        run: curl -X GET https://gym-ai-script.onrender.com/run
